/*
 * Created on 2022-10-22 ( Time 21:21:57 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.gs2e.biblio.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "usager"
 *
 * @author Smile Backend Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="usager" )
public class Usager implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nom", length=50)
    private String     nom          ;

    @Column(name="prenoms", length=100)
    private String     prenoms      ;

    @Column(name="login", length=100)
    private String     login        ;

    @Column(name="passwd", length=100)
    private String     passwd       ;

    @Column(name="email", length=100)
    private String     email        ;

    @Column(name="matricule", length=100)
    private String     matricule    ;

    @Column(name="role_id")
    private Integer    roleId       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at")
    private Date       deletedAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="deleted_by")
    private Integer    deletedBy    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Column(name="contact", length=100)
    private String     contact      ;

    @Column(name="is_connected")
    private Boolean    isConnected  ;

    @Column(name="is_locked")
    private Boolean    isLocked     ;

    @Column(name="is_default_password")
    private Boolean    isDefaultPassword ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_connection_date")
    private Date       lastConnectionDate ;

    @Column(name="is_first_connection")
    private Boolean    isFirstConnection ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Usager() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
