/*
 * Created on 2022-10-22 ( Time 12:04:10 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.gs2e.biblio.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "users"
 *
 * @author Smile Backend Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="users" )
public class Users implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nom", length=50)
    private String     nom          ;

    @Column(name="prenoms", length=100)
    private String     prenoms      ;

    @Column(name="login", length=100)
    private String     login        ;

    @Column(name="passwd", length=100)
    private String     passwd       ;

    @Column(name="email", length=100)
    private String     email        ;

    @Column(name="matricule", length=100)
    private String     matricule    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at")
    private Date       deletedAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="deleted_by")
    private Integer    deletedBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_connection_date")
    private Date       lastConnectionDate ;

    @Column(name="is_connected")
    private Boolean    isConnected  ;

    @Column(name="is_locked")
    private Boolean    isLocked     ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

    @Column(name="is_default_password")
    private Boolean    isDefaultPassword ;

    @Column(name="is_first_connection")
    private Boolean    isFirstConnection ;

    @Column(name="contact", length=100)
    private String     contact      ;

	// "roleId" (column "role_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="role_id", referencedColumnName="id")
    private Role role        ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Users() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
